version: '3.8'

services:
    nginx-exp:
        container_name: nginx-exp
        image: nginx:latest
        ports:
            - "8080:80"
        deploy:
            resources:
                reservations:
                    cpus: "0.25"
                    memory: 50M
                limits:
                    cpus: "0.5"
                    memory: 200M
